---
_yaml:
  _version: 0.3.1
  app: registry
  app_version: 0.1.0
  doc: quiltcore
  doc_version: 0.1.0
dirs:
  config: .quilt
  names: named_packages
  values: packages
resources:
  CoreManifest:
    child: CoreName
    glob: "*"
  CoreName:
    child: CoreManifest
    glob: "*"
  CoreRegistry:
    child: CoreName
    glob: "*/*"
  CoreValues:
    child: CoreBlob
    glob: "*"

type: application/ld+json
